version: "3.5"
services:

  web:
    image: nginx:latest
    volumes:
      - ./config/nginx/keycloak.nginx:/etc/nginx/conf.d/default.conf:ro
      - ./config/certs:/etc/nginx/ssl:ro
#      - ./config/nginx/ssl-optim.nginx:/etc/nginx/nginx-ssl-optim.conf:ro
#      - ./config/nginx/secu-optim.nginx:/etc/nginx/nginx-secu-optim.conf:ro
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
    networks:
      - keycloak-network


  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    depends_on:
      - keycloakDB
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "admin"
      DB_VENDOR: "POSTGRES"
      DB_USER: "keycloak"
      DB_PASSWORD: "password"
      DB_ADDR: "keycloakDB"
      KEYCLOAK_HTTPS_PORT: 401
      PROXY_ADDRESS_FORWARDING: "true"
    ports:
      - "8080:8080"
#    volumes:
#      - "./logs/keycloak:/opt/jboss/keycloak/standalone/log"
    networks:
      keycloak-network:
          aliases:
            - auth.agriprev.loc
            - max


  keycloakDB:
    image: postgres
    environment:
      POSTGRES_DB: "keycloak"
      POSTGRES_USER: "keycloak"
      POSTGRES_PASSWORD: "password" 
    ports:
      - "5432:5432"
    volumes:
      - "keycloakdbdata:/var/lib/postgresql/data"
    networks:
      - keycloak-network

networks:
    keycloak-network:
      driver: bridge

volumes:
  keycloakdbdata:
