version: "3.5"
services:

  apache:
    image: httpd:2.4
    volumes:
      - ./config/nginx/keycloak.nginx:/etc/nginx/conf.d/default.conf:ro
      - ./config/certs:/etc/nginx/ssl:ro
#      - ./config/nginx/ssl-optim.nginx:/etc/nginx/nginx-ssl-optim.conf:ro
#      - ./config/nginx/secu-optim.nginx:/etc/nginx/nginx-secu-optim.conf:ro
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - keycloak
    networks:
      - keycloak-network

networks:
    keycloak-network:
