version: "3.5"
services:

  apache:
   build:
      context: ./docker
    image: jmorille/httpd-oidc:latest
    volumes:
      - ./config/app1-vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/certs:/etc/nginx/ssl:ro
#      - ./config/nginx/ssl-optim.nginx:/etc/nginx/nginx-ssl-optim.conf:ro
#      - ./config/nginx/secu-optim.nginx:/etc/nginx/nginx-secu-optim.conf:ro
      - ./logs/nginx:/var/log/nginx
    ports:
      - "8081:8081"
      - "8443:8443"
    depends_on:
      - keycloak
    networks:
      - keycloak-network

networks:
    keycloak-network:
